### ISSUE TITLE
Unable to install with pip from pypi

### ISSUE THREAD

**Issue by Eeems** [anthony-tuininga/cx_PyOracleLib#2]
When attempting to install with pip, you get the following error (Python 2.7 as well as 3.7):

```
that satisfies the requirement cx_PyOracleLib (from versions: )
No matching distribution found for cx_PyOracleLib
```

I can see the project on pypi (https://pypi.org/project/cx_PyOracleLib/) but there are no downloads listed.

EDIT: You can install it directly from github though: ```pip install git+https://github.com/anthony-tuininga/cx_PyOracleLib.git```

**Comment by anthony-tuininga** [comment]
A good point. I'll look at getting that corrected.

**Comment by anthony-tuininga** [comment]
I've just uploaded the new package to PyPI.
