### ISSUE TITLE
Performance Issue with retrieving objects with indexes

### ISSUE THREAD

**Issue by evan-cx** [anthony-tuininga/cx_PyOracleLib#5]
Please see cx_Oracle issue [#2](https://github.com/anthony-tuininga/cx_OracleTools/issues/2)

I am unable to create a branch and pull request due to repository permissions, so I'm just going to note what I did to fix the issue.

https://github.com/anthony-tuininga/cx_PyOracleLib/blob/main/cx_OracleObject/Statements.py#L68
Add `and table_name = o.table_name` to the query.

**Comment by anthony-tuininga** [comment]
I see you managed to ceate a PR after all. :-) It has now been merged.
